name: flutter_deep_dive

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    linkToCommit: true
    workspaceChangelog: true

scripts:
  analyze:
    description: Run `dart analyze` in all packages
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos

  install_riverpod:
    description: Install Riverpod and related packages in the current directory
    packageFilters:
      flutter: true
    run: |
      melos exec -c 1 "flutter pub add flutter_riverpod riverpod_annotation && flutter pub add --dev riverpod_generator build_runner custom_lint riverpod_lint"

  install_test:
    description: Install test packages
    packageFilters:
      flutter: true
    run: |
      melos exec -c 1 -- flutter pub add --dev mockito build_runner

  test:
    description: Run `flutter test` in all packages
    run: |
      melos exec -c 1 --dir-exists="test" -- \
        flutter test --no-pub
